# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cp_sd <- function(phi, SIGMA, w) {
    .Call(`_PARCOR_cp_sd`, phi, SIGMA, w)
}

get_sd <- function(sd, ts1, ts2, type) {
    .Call(`_PARCOR_get_sd`, sd, ts1, ts2, type)
}

cp_sd_uni <- function(phi, sigma2, w) {
    .Call(`_PARCOR_cp_sd_uni`, phi, sigma2, w)
}

compute_DIC_TVVAR <- function(temp_filter, sample_size, St, P_max) {
    .Call(`_PARCOR_compute_DIC_TVVAR`, temp_filter, sample_size, St, P_max)
}

compute_spec <- function(phi, SIGMA, w, P_max, ch1, ch2, time_depend = TRUE) {
    .Call(`_PARCOR_compute_spec`, phi, SIGMA, w, P_max, ch1, ch2, time_depend)
}

forward_filter_backward_smooth <- function(yt, F1, F2, n_0, S_0, n_t, n_I, m, type, P, delta1, delta2, sample_size) {
    .Call(`_PARCOR_forward_filter_backward_smooth`, yt, F1, F2, n_0, S_0, n_t, n_I, m, type, P, delta1, delta2, sample_size)
}

ffbs_DIC <- function(yt, F1, F2, n_0, S_0, n_t, n_I, m, type, P, delta, DIC, sample_size, chains, uncertainty) {
    .Call(`_PARCOR_ffbs_DIC`, yt, F1, F2, n_0, S_0, n_t, n_I, m, type, P, delta, DIC, sample_size, chains, uncertainty)
}

filter_smooth_TVVAR <- function(F1, G, mk_0, Ck_0, n_0, S_0, m, delta, pp) {
    .Call(`_PARCOR_filter_smooth_TVVAR`, F1, G, mk_0, Ck_0, n_0, S_0, m, delta, pp)
}

filter <- function(F1_fwd, F1_bwd, S_0, m, delta, type_num, P, n_t, n_I, n_I2) {
    .Call(`_PARCOR_filter`, F1_fwd, F1_bwd, S_0, m, delta, type_num, P, n_t, n_I, n_I2)
}

filter_smooth <- function(F1_fwd, F1_bwd, S_0, m, delta, type_num, P, DIC, sample_size, chains, uncertainty) {
    .Call(`_PARCOR_filter_smooth`, F1_fwd, F1_bwd, S_0, m, delta, type_num, P, DIC, sample_size, chains, uncertainty)
}

do_mcmc_sPARCOR <- function(y_fwd, y_bwd, d, niter, nburn, nthin, c0, g0, G0, d1, d2, e1, e2, learn_lambda2, learn_kappa2, lambda2, kappa2, learn_a_xi, learn_a_tau, a_xi, a_tau, a_tuning_par_xi, a_tuning_par_tau, beta_a_xi, beta_a_tau, alpha_a_xi, alpha_a_tau, display_progress, ret_beta_nc, ind, skip, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, adaptive, target_rates, max_adapts, batch_sizes) {
    .Call(`_PARCOR_do_mcmc_sPARCOR`, y_fwd, y_bwd, d, niter, nburn, nthin, c0, g0, G0, d1, d2, e1, e2, learn_lambda2, learn_kappa2, lambda2, kappa2, learn_a_xi, learn_a_tau, a_xi, a_tau, a_tuning_par_xi, a_tuning_par_tau, beta_a_xi, beta_a_tau, alpha_a_xi, alpha_a_tau, display_progress, ret_beta_nc, ind, skip, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, adaptive, target_rates, max_adapts, batch_sizes)
}

run_whittle <- function(phi_fwd, phi_bwd, n_I) {
    .Call(`_PARCOR_run_whittle`, phi_fwd, phi_bwd, n_I)
}

sample_tvar_coef <- function(phi_fwd, phi_bwd, Cnt_fwd, Cnt_bwd, n_I, P_opt, P_max, h) {
    .Call(`_PARCOR_sample_tvar_coef`, phi_fwd, phi_bwd, Cnt_fwd, Cnt_bwd, n_I, P_opt, P_max, h)
}

run_dl <- function(phi_fwd, phi_bwd) {
    .Call(`_PARCOR_run_dl`, phi_fwd, phi_bwd)
}

vi_shrinkTVP <- function(y_fwd, y_bwd, d, d1, d2, e1, e2, a_xi, a_tau, learn_a_xi, learn_a_tau, iter_max, ind, S_0, epsilon, skip, sample_size, b_xi, b_tau) {
    .Call(`_PARCOR_vi_shrinkTVP`, y_fwd, y_bwd, d, d1, d2, e1, e2, a_xi, a_tau, learn_a_xi, learn_a_tau, iter_max, ind, S_0, epsilon, skip, sample_size, b_xi, b_tau)
}

